version: "4.3"

services:
    laravel-app:
        build:
            context: "."
            args:
                uid: ${UID}
        container_name: app-api
        restart: unless-stopped
        ports:
            - 9080:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - .:/var/www/html
        networks:
            backend:
                aliases:
                    - bridge

networks:
    backend:
        name: bridge
