version: "4.3"

services:
    laravel-app:
        build:
            context: "."
            args:
                uid: ${UID}
        container_name: app-api
        restart: unless-stopped
        ports:
            - ${HOST_PORT}:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - .:/var/www/html
        networks:
            backend:
                aliases:
                    - app

    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        restart: unless-stopped        
        volumes:
            - ./run/var:/var/lib/mysql
            #- ./run/dump/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - ${HOST_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=securerootpassword
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            backend:
                aliases:
                    - mysql-db

networks:
    backend:
        name: api-network
