version: "3.1"
services:

    api_mariadb:
      image: mariadb:10.11
      container_name: api_mariadb
      restart: unless-stopped
      tty: true
      volumes:
        - database:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=Ncm@647534
        - MYSQL_DATABASE=base
        - MYSQL_USER=root
        - MYSQL_PASSWORD=pass
      ports:
        - "8031:3306"
      networks:
        - api

    api_nginx:
      image: nginx:alpine
      container_name: api_nginx
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./src:/application
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "10080:80"
      links:
        - api_mariadb
      networks:
        - api

    api_php:
      build: .
      container_name: api_php
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./src:/application
      ports:
        - "9000:9000"  
      networks:
        - api

networks:
  api:
    driver: bridge

volumes:
  database:
    driver: local